### ISSUE TITLE
app-manager adding 'Connection: close' to response headers of client simulation requests

### ISSUE THREAD

**Issue by flawmop** [CardiacModelling/ap-nimbus-app-manager#4]
Currently, _app-manager_ is instructing _client_ to close the HTTP connection each time a simulation is invoked, rather than [keep it alive](https://en.wikipedia.org/wiki/HTTP_persistent_connection), because that was the way it was designed(*) prior to CellML and PKPD being allowed in ap-nimbus. This behaviour is described in [server.js](https://github.com/CardiacModelling/ap-nimbus-app-manager/blob/3be2ea2e4ba9f90655d6dba28282e9489bf8e536/server.js#L933-L954), and can be overridden "on-demand" by calling _app-manager_ with the `keep_alive` URL param, e.g. by changing the env file property `AP_PREDICT_ENDPOINT=http://name-app-manager:8080/keep_alive`.

I've been running some tests locally and it looks like Django perhaps unsurprisingly has a problem with the disconnecting when passing CellML files to _app-manager_ (although it may also happen with PKPD files). What seems to be happening is that one or two simulations may run successfully, but thereafter they'll start to fail after first displaying a status of "Converting CellML...". I'd be interested to know @MauriceHendrix if you've experienced something like this while you were testing, as Django doesn't appear to behave consistently, i.e. sometimes it may fail on the first simulation, but usually it's within the first five simulations!

I've tried to get some Django trace-level logging set up (to add to the [other logging task](https://github.com/CardiacModelling/ap-nimbus-client/issues/99)) to see exactly what Django's doing and how it responds (because in theory it should complain if it can't send the complete HTTP request), but it appears that [trace level debugging is not an option](https://github.com/CardiacModelling/ap-nimbus-client/issues/99#issuecomment-1536758210), only some basic debug-level request info appears in the logs, which doesn't tell us much.

As we are not going down the route of multiple _app-manager_ availability, I think we may as well just comment out https://github.com/CardiacModelling/ap-nimbus-app-manager/blob/3be2ea2e4ba9f90655d6dba28282e9489bf8e536/server.js#L951-L954 and add a comment referring to this issue.

(*) Originally, it was expected that _client_ would call _app-manager_ with an ApPredict invocation instruction and _app-manager_ would respond to the _client_ with a unique identifier and the HTTP header instruction to close the connection (because the expectation was that there may be many _app-manager_ s available to be serviced and we didn't want sticky connections between a _client_ and a single _app-manager_). Thereafter _client_ and _app-manager_ would communicate only with an independent _datastore_, to retrieve/send results respectively using the unique identifier.

**Comment by MauriceHendrix** [comment]
Although the portal has been tested by a good number of people I don't think may upload cellml files. I haven't seen it myself. I didn't realise that the app-manager doesn't close it's connections, I don't see how that makes any sense to keep them open.

**Comment by flawmop** [comment]
Currently the _app-manager_ is instructing _client_ to close the connection in the response to the simulation request (my understanding is because generally opening connections takes a bit of resource and are therefore kept open/"alive" for a short period (e.g. 90 seconds?) in HTTP in anticipation of another request arriving from the same client).
What I think may cause a problem is in the case of sending a v. large file in a request which a _client_ will break down into chunks and so it may get a bit huffy if it's told to close the connection after sending the first chunk.
